# Generated by Django 3.1.6 on 2021-02-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_applications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
    ]
