# Generated by Django 3.1.6 on 2021-02-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210204_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='experience',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('E', 'Expert')], default='B', max_length=1),
        ),
    ]
