# Generated by Django 3.1.6 on 2021-02-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210204_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='experience',
        ),
    ]
